# Generated by Django 4.2 on 2023-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('repetition', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Every day'), (3, 'Every Week'), (4, 'Once a month')])),
            ],
        ),
    ]
