# Generated by Django 4.2 on 2023-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repetition',
            field=models.CharField(choices=[('Never', 'Never'), ('Every Day', 'Every Day'), ('Every Week', 'Every Week'), ('Every Month', 'Every Month'), ('Every Year', 'Every Year')], default='Never', max_length=20),
        ),
    ]
