# Generated by Django 4.2 on 2023-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_event_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Task', 'Task'), ('Schedule', 'Schedule')], default='Task', max_length=20),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
