# Generated by Django 4.2 on 2023-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='ts_date',
            field=models.DateField(),
        ),
    ]
