# Generated by Django 4.2 on 2023-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_timerecord_ts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='ts_date',
            field=models.DateTimeField(),
        ),
    ]
