# Generated by Django 4.2 on 2023-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_appointment_task_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='repetition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Every day'), (3, 'Every week'), (4, 'Once a month')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='importancy_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')]),
        ),
    ]
