# Generated by Django 4.2 on 2023-05-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_timerecord_ts_date'),
        ('playground', '0005_alter_appointment_repetition_and_more'),
    ]

    operations = [
    ]
