# Generated by Django 4.2 on 2023-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_merge_20230522_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRecord',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repetition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Every day'), (3, 'Every Week'), (4, 'Once a month')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
