# Generated by Django 4.2 on 2023-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_delete_timerecord_alter_appointment_repetition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
        ),
    ]
