# Generated by Django 4.2 on 2023-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_personalpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpreference',
            name='name',
            field=models.CharField(default='Preference', max_length=50),
            preserve_default=False,
        ),
    ]
